### ISSUE TITLE
RQ job timeout errors during quote updates polling on the "watchlist" page

### ISSUE THREAD

**Issue by Willamette-OR** [Willamette-OR/invresearch#13]
Two unhandled exceptions right now, whenever RQ stops the quote polling job after the pre-specified timeout value is exceeded: 

1. RQ throws an exception from the app.tasks module, for the task function can no longer be executed by the RQ worker after exceeding the timeout value. See below for the detailed error message.
2. The view function for "/refresh_quote_polling" throws an exception from the app.routes module, since task.get_rq_job() can no longer get a corresponding job object from the job queue (after job termination due to timeout). See below for the detailed error message.

**Error message for issue 1 above:**

[2021-09-27 15:26:16,008] [ERROR] in [tasks]: Unhandled exceptions
Traceback (most recent call last):
  File "/home/baiber/projects/invresearch/./app/tasks.py", line 140, in refresh_quotes
    sleep(seconds)
  File "/home/baiber/projects/invresearch/venv/lib/python3.8/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value '
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (1200 seconds)

**Error message for issue 2 above:**

[2021-09-27 15:26:35,174] [ERROR] in [app]: Exception on /refresh_quote_polling [GET]
Traceback (most recent call last):
  File "/home/baiber/projects/invresearch/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/baiber/projects/invresearch/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/baiber/projects/invresearch/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/baiber/projects/invresearch/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/baiber/projects/invresearch/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/baiber/projects/invresearch/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/baiber/projects/invresearch/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/baiber/projects/invresearch/app/main/routes.py", line 538, in refresh_quote_polling
    job = task.get_rq_job()
AttributeError: 'NoneType' object has no attribute 'get_rq_job'

**Comment by Willamette-OR** [comment]
The error should be able to get more quickly reproduced by changing the "job_timeout" value, a key word argument when launching the task (current_user.launch_task) from the view function for '/watchlist', from within app.routes.
